### ISSUE TITLE
Freeze after choosing a lsp-offered completion candidate

### ISSUE THREAD

**Issue by kenji0923** [Shougo/ddc-source-lsp#63]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
After choosing a lsp-offered completion candidate, vim seems to be freezed.
In my testing, the problem occurs for TeX and python LSP, but not for C++.

## Expected
There should be no freeze as C++-LSP source or other sources, which is for instance ddc-source-around.
ddc-source-around did not freeze vim even when I checked in TeX and python files.

## Environment Information

- ddc.vim version (SHA1): 713725a5e5a67e1298dc07720c6be94075610534 

- denops.vim version (SHA1): eb9ef6a6a43475f9a2b3cdfa682aa6887169a50c 

- deno version(`deno -V` output): deno 1.45.5

- OS: Red Hat Enterprise Linux 9.4

- neovim/Vim `:version` output:
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Aug 16 2024 10:57:14)
適用済パッチ: 1-678
Compiled by
Huge 版 without GUI.  機能の一覧 有効(+)/無効(-)
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             +xattr
-dnd               -mouseshape        +spell             -xfontset
-ebcdic            +mouse_dec         +startuptime       -xim
+emacs_tags        -mouse_gpm         +statusline        -xpm
+eval              -mouse_jsbterm     -sun_workshop      -xsmp
+ex_extra          +mouse_netterm     +syntax            -xterm_clipboard
+extra_search      +mouse_sgr         +tag_binary        -xterm_save
-farsi             -mouse_sysmouse    -tag_old_static
      システム vimrc: "$VIM/vimrc"
      ユーザー vimrc: "$HOME/.vimrc"
   第2ユーザー vimrc: "~/.vim/vimrc"
   第3ユーザー vimrc: "~/.config/vim/vimrc"
       ユーザー exrc: "$HOME/.exrc"
  デフォルトファイル: "$VIMRUNTIME/defaults.vim"
       省略時の $VIM: "/usr/local/share/vim"
コンパイル: gcc -c -I. -Iproto -DHAVE_CONFIG_H -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
リンク: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -lselinux -L/usr/lib -lluajit-5.1 -L/usr/lib64/python3.9/config-3.9-x86_64-linux-gnu -lpython3.9 -lcrypt -ldl -lm -lm

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
let s:working_dir = expand('~/tmp/2024-08-16_ddc-source-lsp/')

execute 'set runtimepath+=' .. s:working_dir .. 'denops.vim'
execute 'set runtimepath+=' .. s:working_dir .. 'vim-lsp'
execute 'set runtimepath+=' .. s:working_dir .. 'vim-lsp-settings'
execute 'set runtimepath+=' .. s:working_dir .. 'ddc.vim'
execute 'set runtimepath+=' .. s:working_dir .. 'ddc-ui-native'
execute 'set runtimepath+=' .. s:working_dir .. 'ddc-source-lsp'
execute 'set runtimepath+=' .. s:working_dir .. 'ddc-source-around'

function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
endfunction

augroup lsp_install
    autocmd!
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

call ddc#custom#patch_global('ui', 'native')

call ddc#custom#patch_global('sources', ['around', 'lsp'])

call ddc#custom#patch_global('sourceOptions', {
            \   'around': {
            \       'mark': 'aro',
            \   },
            \   'lsp': {
            \       'mark': 'lsp',
            \       'forceCompletionPattern': '\.\w*|:\w*|->\w*',
            \   },
            \ })

call ddc#custom#patch_global('sourceParams', {
            \   'lsp': {
            \       'lspEngine': 'vim-lsp',
            \       'enableAdditionalTextEdit': v:true,
            \       'enableResolveItem': v:true,
            \       'enableDisplayDetail': v:true,
            \   },
            \ })

call ddc#enable()

filetype indent plugin on
syntax on
```

## How to reproduce the problem from neovim/Vim startup (Required!)

LSPs are installed according the prompts by vim-lsp-settings plugin.

### In a TeX file
1. vim main.tex
2. Type "\do"
3. Press CTRL-n to select "documentclass  Function lsp built-in"
4. Press "{", and it freezes a bit
5. Break some lines
6. Type "docu" and select "documentclass  aro" by pressing CTRL-n
7. Press "{". This time there is no freezing to add "{" character after the completion.

### In a python file
1. vim main.py
2. Type "imp"
3. Press CTRL-n to select "import  Keyword lsp"
4. Press the space key, and it freezes a bit to have a single space after the word "import"

### In a C++ file
1. vim main.cpp
2. Type "#include <io"
3. Press CTRL-n to select "iostream>  File lsp"
4. Press the enter key to have a line break. This time, there was no freeze.

**Comment by Shougo** [comment]
Reproduced.  But it seems not `ddc-source-lsp` problem.

**Comment by Shougo** [comment]
Hm....

`            \       'enableResolveItem': v:false,`  It seems very slow.

**Comment by Shougo** [comment]
`onCompleteDone` is executed asynchronously.

**Comment by kenji0923** [comment]
Thank you very much! It now works.
